# In _config.yml
title: OpenAlea gallery
subtitle: A collection of examples and tutorials for OpenAlea
author: The Jupyter Book Community
copyright: "2025, OpenAlea Team"
logo: _static/openalea_web.svg
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - reference/references.bib

# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: false
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true

# Information about where the book exists on the web
repository:
  url: "https://github.com/openalea/gallery"
  branch: main

launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  notebook_interface: "jupyterlab"  # or "classic"
  #jupyterhub_url: "https://jupyterhub.macs4plants.cirad.fr"  # The URL for your JupyterHub.
                  # Needs nbgitpuller and jupytext installed on the JupyterHub,
                  # cf. https://jupyterbook.org/en/stable/interactive/launchbuttons.html#add-a-launch-on-jupyterhub-button